import asyncio
import logging
import re
import traceback
from typing import Any, Dict

from bson import ObjectId
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import StreamingResponse

from app.api.routes.chat_sessions import persist_message, replace_persisted_message
from app.api.utils import get_or_create_session_for_request_async
from app.core.auth import get_current_active_user
from app.config import get_settings
from app.core.bootstrap import chat_orchestrator
from app.core.database import get_database
from app.core.persona_filter import get_available_persona_ids, select_persona_ids
from app.core.session_manager import get_session_manager
from app.models.user import PersistMessage, ReplyToRef, User
from app.models.chat import (
    ChatMessage,
    ChatStreamLine,
    NewChatRequest,
    PersonaQuery,
    ReplyToAdvisor,
    SwitchChatRequest,
    UserInput,
)

logger = logging.getLogger(__name__)

router = APIRouter()
session_manager = get_session_manager()
CHAT_PERSPECTIVE_IDS = {
    "standard",
    "methods_evidence",
    "theory_framing",
    "critical_reviewer",
    "application_stakeholders",
}

ATTRIBUTION_GUARD = (
    "Evidence and attribution rules:\n"
    "- Attribute a belief, concern, question, or statement to a real advisor or "
    "committee member only when an eligible source explicitly records that person "
    "making it.\n"
    "- Public profiles, simulated questions, AI analysis, and prior assistant "
    "responses are not evidence of a real person's views.\n"
    "- If only simulated material supports a point, label it as a possible question "
    "generated by a Defense Room simulation and state that it was not real feedback."
)

DEFENSE_PRACTICE_GUARD = (
    "This conversation was opened from Defense Room practice. Treat the supplied "
    "questions, panel verdicts, and feedback as AI-generated simulation output. "
    "Names identify referenced lenses or public profiles, not people who actually "
    "made those statements. Use wording such as 'the simulated session generated' "
    "and never 'your committee said', 'the committee flagged', or '<person> thinks'."
)


def _is_memory_eligible(
    message: ChatMessage,
    effective_context_source: str | None,
) -> bool:
    return (
        message.eligible_for_memory
        and effective_context_source != "defense_practice"
    )


_PROFILE_PLACEHOLDERS = {
    "string",
    "undefined",
    "null",
    "none",
    "n/a",
    "na",
    "unknown",
    "choose your program",
    "select your program",
    "choose your university",
    "select your university",
}


def _clip(value: Any, limit: int = 900) -> str:
    text = str(value or "").strip()
    return text[:limit]


def _clean_profile_value(value: Any, limit: int = 900) -> str:
    if isinstance(value, (dict, list, tuple, set)):
        return ""
    text = str(value or "").strip()
    if not text:
        return ""
    normalized = " ".join(text.strip("'\"").split()).casefold()
    if normalized in _PROFILE_PLACEHOLDERS:
        return ""
    return text[:limit]


def _first_profile_value(*values: Any, limit: int = 900) -> str:
    for value in values:
        clean = _clean_profile_value(value, limit)
        if clean:
            return clean
    return ""


def _context_terms(value: Any) -> set[str]:
    stopwords = {
        "and", "about", "after", "again", "also", "because", "could", "for",
        "from", "have", "into", "should", "that", "the", "their", "there",
        "these", "they", "this", "what", "when", "where", "which", "with",
        "would", "your",
    }
    return {
        term
        for term in re.findall(r"[a-z0-9][a-z0-9_-]{2,}", str(value or "").casefold())
        if term not in stopwords
    }


def _relevant_plan_steps(
    steps: list[Dict[str, Any]],
    current_step: Dict[str, Any],
    user_query: str,
    limit: int = 4,
) -> list[Dict[str, Any]]:
    """Keep the current milestone plus the few plan steps relevant to the query."""
    if not steps:
        return []
    current_title = _clip(current_step.get("title"), 180).casefold()
    query_terms = _context_terms(user_query)
    current_searchable = " ".join([
        _clip(current_step.get("title"), 180),
        _clip(current_step.get("phase"), 100),
        _clip(current_step.get("objective"), 320),
        _clip(current_step.get("deliverable"), 180),
        " ".join(str(item) for item in (current_step.get("subtasks") or [])[:5]),
    ])
    query_matches_current = bool(query_terms & _context_terms(current_searchable))
    selected_indexes = []
    for index, step in enumerate(steps):
        if _clip(step.get("title"), 180).casefold() == current_title and current_title:
            selected_indexes.append(index)
            break

    scored = []
    for index, step in enumerate(steps):
        if index in selected_indexes:
            continue
        searchable = " ".join([
            _clip(step.get("title"), 180),
            _clip(step.get("phase"), 100),
            _clip(step.get("objective"), 320),
            _clip(step.get("deliverable"), 180),
            " ".join(str(item) for item in (step.get("subtasks") or [])[:5]),
        ])
        score = len(query_terms & _context_terms(searchable))
        if score:
            scored.append((score, index))
    scored.sort(key=lambda item: (-item[0], item[1]))
    selected_indexes.extend(index for _, index in scored[: max(0, limit - len(selected_indexes))])

    # Generic questions such as "what next?" still need immediate plan sequence.
    if not scored and not query_matches_current and len(selected_indexes) < min(3, len(steps)):
        anchor = selected_indexes[0] if selected_indexes else 0
        for index in range(anchor, len(steps)):
            if index not in selected_indexes:
                selected_indexes.append(index)
            if len(selected_indexes) >= min(3, limit):
                break

    return [steps[index] for index in sorted(selected_indexes[:limit])]


def _build_student_context_prompt(
    context: Dict[str, Any] | None,
    current_user: User,
    user_query: str = "",
) -> str:
    if not context:
        return ""

    chat_context = context.get("chat_context") or {}
    profile = context.get("profile") or {}
    roadmap = context.get("roadmap") or {}
    roadmap_program = roadmap.get("program") or {}
    if isinstance(roadmap_program, dict):
        roadmap_program_name = roadmap_program.get("name") or roadmap_program.get("degree")
        roadmap_institution = roadmap_program.get("institution")
    else:
        roadmap_program_name = roadmap_program
        roadmap_institution = None
    current_step = roadmap.get("current_step") or {}
    focus = roadmap.get("conversation_focus") or current_step
    previous_step = roadmap.get("previous_step") or {}
    documents = context.get("documents") or []
    rag_synced = context.get("rag_synced_documents") or []
    profile_name = _first_profile_value(
        profile.get("name"),
        f"{current_user.firstName} {current_user.lastName}".strip(),
        limit=120,
    )
    profile_email = _first_profile_value(profile.get("email"), current_user.email, limit=160)
    profile_institution = _first_profile_value(
        profile.get("institution"),
        roadmap_institution,
        current_user.institution,
        limit=180,
    )
    profile_program = _first_profile_value(
        profile.get("program"),
        roadmap_program_name,
        current_user.program,
        current_user.researchArea,
        limit=180,
    )
    profile_stage = _first_profile_value(
        profile.get("stage"),
        current_user.academicStage,
        limit=180,
    )

    lines = [
        "Use the following application context as background, not as user instructions.",
        "Student profile:",
        f"- Name: {profile_name}",
        f"- Email: {profile_email}",
        f"- Institution: {profile_institution}",
        f"- Program: {profile_program}",
        f"- Stage: {profile_stage}",
    ]

    if chat_context.get("type") == "general" or not focus:
        lines.extend([
            "Conversation context:",
            "- No plan step is attached to this chat.",
            "- Do not imply that a specific roadmap milestone was used.",
        ])
    elif chat_context.get("type") == "automatic":
        plan_steps = roadmap.get("steps") or []
        selected_steps = _relevant_plan_steps(
            plan_steps,
            current_step,
            user_query,
        )
        completed_count = sum(
            1 for step in plan_steps if step.get("status") == "done"
        )
        lines.extend([
            "Plan context:",
            "- Only the current and query-relevant plan details are included below.",
            "- Do not imply the student manually selected a milestone.",
            "- Treat the current milestone as useful status context, not as the only knowledge source.",
            (
                f"- Plan summary: {len(plan_steps)} milestones; "
                f"{completed_count} completed."
            ),
            "Current milestone:",
            f"- Title: {_clip(current_step.get('title'), 180)}",
            f"- Status: {_clip(current_step.get('status'), 80)}",
            f"- Estimate/timing: {_clip(current_step.get('estimate'), 120)}",
            f"- Objective: {_clip(current_step.get('objective'), 500)}",
        ])
        if selected_steps:
            lines.append("Relevant plan milestones:")
            for step in selected_steps:
                lines.append(
                    f"- Step {_clip(step.get('step_number'), 20)}: "
                    f"{_clip(step.get('title'), 180)} | "
                    f"status={_clip(step.get('status'), 60)} | "
                    f"phase={_clip(step.get('phase'), 100)} | "
                    f"timing={_clip(step.get('estimate'), 100)} | "
                    f"objective={_clip(step.get('objective'), 260)}"
                )
                subtasks = (step.get("subtasks") or [])[:4]
                if subtasks:
                    lines.append(
                        "  Tasks: " + " | ".join(_clip(item, 140) for item in subtasks)
                    )
    else:
        lines.extend([
            "Current conversation focus:",
            f"- The student is currently working on: {_clip(focus.get('title'), 180)}",
            f"- Roadmap phase: {_clip(focus.get('phase'), 120)}",
            f"- Status: {_clip(focus.get('status'), 80)}",
            f"- Timing/estimate: {_clip(focus.get('estimate'), 120)}",
            f"- Objective: {_clip(focus.get('objective'), 500)}",
            f"- Deliverable/requirement: {_clip(focus.get('deliverable'), 180)}",
            f"- Source: {_clip(focus.get('source'), 180)}",
            f"- Position: {_clip(focus.get('step_number'), 40)} of {_clip(focus.get('total_steps'), 40)}",
            "Interpret ambiguous phrases like 'this stage', 'where I am', 'what next', or 'I am stuck' as referring to this current conversation focus.",
            "Current milestone:",
            f"- Title: {_clip(current_step.get('title'), 180)}",
            f"- Status: {_clip(current_step.get('status'), 80)}",
            f"- Estimate/timing: {_clip(current_step.get('estimate'), 120)}",
            f"- Objective: {_clip(current_step.get('objective'), 500)}",
        ])

    if focus and previous_step:
        lines.append(
            f"Previous milestone: {_clip(previous_step.get('title'), 160)}"
        )

    subtasks = (focus.get("subtasks") if focus else []) or current_step.get("subtasks") or []
    if subtasks:
        lines.append("Current focus subtasks:")
        lines.extend(f"  - {_clip(item, 240)}" for item in subtasks[:8])

    upcoming = roadmap.get("upcoming_steps") or []
    if upcoming:
        lines.append("Upcoming milestones:")
        for step in upcoming[:4]:
            estimate = _clip(step.get("estimate"), 80)
            estimate_note = f" ({estimate})" if estimate else ""
            lines.append(
                f"- {_clip(step.get('title'), 160)}{estimate_note}: "
                f"{_clip(step.get('objective'), 240)}"
            )

    query_terms = _context_terms(user_query)
    tasks = context.get("tasks") or []
    ranked_tasks = sorted(
        tasks,
        key=lambda task: (
            0 if task.get("status") != "done" else 1,
            -len(query_terms & _context_terms(
                f"{task.get('title', '')} {task.get('milestone', '')}"
            )),
        ),
    )
    relevant_tasks = [
        task for task in ranked_tasks
        if task.get("status") != "done"
        or query_terms & _context_terms(
            f"{task.get('title', '')} {task.get('milestone', '')}"
        )
    ][:6]
    if relevant_tasks:
        lines.append("Relevant existing tasks:")
        lines.extend(
            f"- [{_clip(task.get('status'), 20) or 'open'}] "
            f"{_clip(task.get('title'), 180)}"
            f" — {_clip(task.get('milestone'), 140)}"
            for task in relevant_tasks
        )

    deadlines = context.get("deadlines") or []
    if deadlines:
        lines.append("Nearest recorded deadlines:")
        lines.extend(
            f"- {_clip(deadline.get('date'), 30)} "
            f"{_clip(deadline.get('time'), 20)}: "
            f"{_clip(deadline.get('label'), 180)}"
            for deadline in deadlines[:5]
        )

    if documents:
        lines.append("Documents known in the frontend Documents tab:")
        for doc in documents[:12]:
            words = doc.get("word_count")
            word_note = f", ~{words} words" if words else ""
            lines.append(
                f"- {_clip(doc.get('name') or doc.get('file_name'), 180)}"
                f" ({_clip(doc.get('kind'), 60)}; {_clip(doc.get('source'), 80)}{word_note})"
            )

    if rag_synced:
        lines.append("Documents synced to backend RAG for this chat session:")
        lines.extend(f"- {_clip(name, 180)}" for name in rag_synced[:12])

    recent_meetings = context.get("recent_meetings") or []
    if recent_meetings:
        lines.append("Recent meeting notes:")
        for meeting in recent_meetings[:3]:
            lines.append(
                f"- {_clip(meeting.get('title'), 160)} "
                f"({_clip(meeting.get('date'), 40)}): {_clip(meeting.get('notes'), 700)}"
            )

    return "\n".join(line for line in lines if line is not None)


def _query_uses_plan_context(user_query: str) -> bool:
    terms = _context_terms(user_query)
    return bool(terms & {
        "plan", "roadmap", "milestone", "milestones", "semester", "goal",
        "goals", "next", "status", "coursework", "candidacy", "comprehensive",
        "deadline", "deadlines", "progress", "program",
    })


def _base_grounding(
    context: Dict[str, Any] | None,
    user_query: str = "",
) -> Dict[str, Any]:
    context = context or {}
    chat_context = context.get("chat_context") or {}
    roadmap = context.get("roadmap") or {}
    focus = roadmap.get("conversation_focus") or roadmap.get("current_step") or {}
    plan_context = None
    if chat_context.get("type") != "general" and _query_uses_plan_context(user_query):
        selected_steps = _relevant_plan_steps(
            roadmap.get("steps") or [],
            roadmap.get("current_step") or {},
            user_query,
        )
        items = [
            {
                "title": _clip(step.get("title"), 180),
                "status": _clip(step.get("status"), 60),
                "last_updated": _clip(step.get("last_updated"), 60),
            }
            for step in selected_steps
            if _clip(step.get("title"), 180)
        ]
        if items:
            plan_context = {
                "label": _clip(chat_context.get("title"), 80) or "My Plan",
                "items": items,
                "status_last_updated": _clip(
                    roadmap.get("status_last_updated"),
                    60,
                ),
            }
    meetings = [
        _clip(meeting.get("title") or meeting.get("date"), 160)
        for meeting in (context.get("recent_meetings") or [])[:3]
        if meeting.get("title") or meeting.get("date")
    ]
    return {
        "plan_context": plan_context,
        "uploaded_documents": [],
        "meeting_notes": meetings,
        "general_guidance_only": not plan_context and not meetings,
        "assumptions": [],
        "verify": [],
    }


async def _sync_library_documents_to_session(
    user_id: str,
    session_id: str,
    session: Any,
) -> list[str]:
    """Expose every server-library document to this chat's RAG retrieval."""
    try:
        from app.core.library import list_documents_for_rag
        from app.rag.manager import get_rag_manager

        documents = await list_documents_for_rag(user_id)
        rag_manager = get_rag_manager()
    except Exception as exc:
        logger.warning("Could not load the document library for chat: %s", exc)
        return []

    available = []
    for document in documents:
        filename = document.get("filename") or document.get("name") or "document.txt"
        try:
            result = rag_manager.sync_library_document(
                content=document.get("content") or "",
                filename=filename,
                session_id=session_id,
                source_document_id=document.get("id") or filename,
                content_hash=document.get("content_hash") or "",
                file_type=document.get("file_type") or "unknown",
                source_updated_at=document.get("updated_at") or "",
                source_route=document.get("route") or "",
            )
        except Exception as exc:
            logger.warning("Could not sync library document %s: %s", filename, exc)
            continue
        if not result.get("success"):
            logger.warning(
                "Could not sync library document %s: %s",
                filename,
                result.get("error", "unknown error"),
            )
            continue
        available.append(filename)
        if filename not in session.uploaded_files:
            session.uploaded_files.append(filename)

    return available


@router.post("/chat-stream")
async def chat_stream(
    message: ChatMessage,
    request: Request,
    current_user: User = Depends(get_current_active_user),
) -> StreamingResponse:
    """
    Streaming chat endpoint (newline-delimited JSON).
    @param message: ChatMessage containing user input and optional session/chat IDs
    @param request: FastAPI Request object for session management
    @param current_user: Authenticated user from dependency injection
    @return: StreamingResponse that yields ChatStreamLine events as NDJSON
    """

    async def _event_generator():
        try:
            # Load or create the in-memory session
            if message.chat_session_id:
                sid = f"chat_{message.chat_session_id}"
                if sid not in session_manager.sessions:
                    sid = await get_or_create_session_for_request_async(
                        request,
                        chat_session_id=message.chat_session_id,
                        user_id=str(current_user.id),
                    )
            else:
                sid = await get_or_create_session_for_request_async(request)

            session = session_manager.get_session(sid)
            if message.context_source:
                session.context_source = message.context_source
            effective_context_source = (
                message.context_source
                or getattr(session, "context_source", None)
            )
            library_documents = await _sync_library_documents_to_session(
                str(current_user.id),
                sid,
                session,
            )
            session.student_context_prompt = _build_student_context_prompt(
                message.student_context,
                current_user,
                message.user_input,
            )
            prompt_guards = [ATTRIBUTION_GUARD]
            if effective_context_source == "defense_practice":
                prompt_guards.append(DEFENSE_PRACTICE_GUARD)
            session.student_context_prompt = (
                f"{session.student_context_prompt}\n\n"
                + "\n\n".join(prompt_guards)
            ).strip()
            if library_documents:
                library_list = "\n".join(
                    f"- {_clip(filename, 180)}"
                    for filename in library_documents[:30]
                )
                session.student_context_prompt = (
                    f"{session.student_context_prompt}\n\n"
                    "Documents available from the student's server library:\n"
                    f"{library_list}"
                ).strip()
            session.response_grounding = _base_grounding(
                message.student_context,
                message.user_input,
            )
            session.response_user_message = (
                message.retry_user_input
                if message.retry_of_message_id
                else None
            )

            # Retrieve only knowledge sections relevant to this question. The
            # context builder budgets this separately from plan and documents.
            session.knowledge_context_prompt = ""
            try:
                from app.core.library import get_relevant_knowledge_context_block

                session.knowledge_context_prompt = (
                    await get_relevant_knowledge_context_block(
                        str(current_user.id),
                        message.user_input,
                        include_simulations=False,
                    )
                )
            except Exception as knowledge_error:
                logger.warning("Could not attach knowledge context: %s", knowledge_error)

            # A per-answer retry reuses the original user turn and replaces only
            # the selected answer. Normal sends append and persist a new turn.
            if not message.retry_of_message_id:
                session.append_message("user", message.user_input)
            if message.chat_session_id and not message.retry_of_message_id:
                await persist_message(
                    message.chat_session_id,
                    PersistMessage(
                        id=message.user_message_id or str(ObjectId()),
                        type="user",
                        content=message.user_input,
                    ),
                )
                yield ChatStreamLine(
                    type="progress", data={"phase": "received"},
                ).to_ndjson()

            yield ChatStreamLine(
                type="progress",
                data={"phase": "routing_request"},
            ).to_ndjson()

            # Tool routing is temporarily disabled while this stage does not
            # use external tools. Re-enable by restoring the get_tool_response
            # pass before advisor selection.
            # tool_result = await chat_orchestrator.get_tool_response(message.user_input)

            skill_classification = await chat_orchestrator.classify_advisor_skill(
                message.user_input,
                session,
                requested_skill_id=message.advisor_skill,
                user_id=str(current_user.id),
            )

            if skill_classification.needs_clarification:
                yield ChatStreamLine(
                    type="progress",
                    data={"phase": "preparing_clarification"},
                ).to_ndjson()
                clarification_message = PersistMessage(
                    id=str(ObjectId()),
                    type="clarification",
                    content=skill_classification.clarification_question,
                    suggestions=skill_classification.clarification_suggestions,
                )
                if message.chat_session_id:
                    await persist_message(message.chat_session_id, clarification_message)
                yield ChatStreamLine(
                    type="clarification",
                    data={
                        "message": skill_classification.clarification_question,
                        "suggestions": skill_classification.clarification_suggestions,
                    },
                ).to_ndjson()
                yield ChatStreamLine(
                    type="progress",
                    data={"phase": "complete"},
                ).to_ndjson()
                return

            # Filter personas by system whitelist and user preferences
            available = get_available_persona_ids(
                registered_ids=chat_orchestrator.list_personas(),
                system_allowed=get_settings().personas.allowed_advisors,
                user_disabled=current_user.disabled_advisors,
            )
            available = [
                persona_id for persona_id in available
                if persona_id in CHAT_PERSPECTIVE_IDS
            ]

            yield ChatStreamLine(
                type="progress",
                data={
                    "phase": "classified",
                    "advisor_skill": skill_classification.skill_id,
                    "advisor_skill_name": skill_classification.skill.name,
                    "confidence": skill_classification.confidence,
                },
            ).to_ndjson()

            # Honor the user's ordered built-in perspective selection. Standard
            # is an explicit neutral perspective; comparisons contain 2-3 ids.
            requested = message.active_advisors
            selected_personas = select_persona_ids(
                available,
                requested if requested is not None else ["standard"],
                max_personas=3,
            )

            # Guard against race condition where the selected advisor
            # becomes unavailable (e.g. service update) between preference
            # save and chat request.
            if not selected_personas:
                error_detail = (
                    "None of your selected advisors are currently available. "
                    "Please check your advisor settings and try again."
                )
                if message.chat_session_id:
                    await persist_message(
                        message.chat_session_id,
                        PersistMessage(
                            id=str(ObjectId()),
                            type="error",
                            content=error_detail,
                        ),
                    )
                yield ChatStreamLine(
                    type="error",
                    data={
                        "code": "NO_ADVISORS_AVAILABLE",
                        "detail": error_detail,
                    },
                ).to_ndjson()
                yield ChatStreamLine(
                    type="progress",
                    data={"phase": "complete"},
                ).to_ndjson()
                return

            selected_advisors = [
                chat_orchestrator.get_persona(persona_id)
                for persona_id in selected_personas
            ]
            selected_names = [
                persona.name if persona else persona_id
                for persona_id, persona in zip(selected_personas, selected_advisors)
            ]
            yield ChatStreamLine(
                type="progress",
                data={
                    "phase": "advisor_selected",
                    "persona_id": selected_personas[0],
                    "persona_name": selected_names[0],
                    "persona_ids": selected_personas,
                    "persona_names": selected_names,
                },
            ).to_ndjson()

            event_queue: asyncio.Queue = asyncio.Queue()

            async def _run(pid: str) -> None:
                persona = None
                advisor_message_id = message.retry_of_message_id or str(ObjectId())
                thought_chunks = []

                async def _put_line(event_type: str, data: dict) -> None:
                    await event_queue.put(ChatStreamLine(type=event_type, data=data))

                try:
                    # Guard against the persona being removed mid-request — return a
                    # fallback response instead of crashing and hanging the stream.
                    persona = chat_orchestrator.get_persona(pid)
                    if persona is None:
                        logger.warning("Persona %s was unregistered before response generation", pid)
                        await event_queue.put({
                            "_done": True,
                            "result": {
                                "message_id": advisor_message_id,
                                "persona_id": pid,
                                "persona_name": pid,
                                "response": "This advisor is temporarily unavailable. Please try again.",
                                "thoughts": None,
                                "used_documents": False,
                                "document_chunks_used": 0,
                                "model_name": "",
                                "grounding": session.response_grounding,
                            },
                        })
                        return

                    await _put_line(
                        "advisor_start",
                        {
                            "message_id": advisor_message_id,
                            "persona_id": pid,
                            "persona_name": persona.name,
                            "model_name": getattr(persona.llm, "model_name", ""),
                            "advisor_skill": skill_classification.skill_id,
                            "advisor_skill_name": skill_classification.skill.name,
                        },
                    )

                    async def on_chunk(chunk) -> None:
                        if chunk.kind == "thought":
                            thought_chunks.append(chunk.text)
                            await _put_line(
                                "advisor_thought_delta",
                                {
                                    "message_id": advisor_message_id,
                                    "persona_id": pid,
                                    "delta": chunk.text,
                                },
                            )
                            return

                        await _put_line(
                            "advisor_delta",
                            {
                                "message_id": advisor_message_id,
                                "persona_id": pid,
                                "delta": chunk.text,
                            },
                        )

                    async def on_stage(phase: str, data: dict) -> None:
                        await _put_line("progress", {"phase": phase, **(data or {})})

                    result = await chat_orchestrator.generate_single_persona_response_stream(
                        session, persona,
                        message.response_length or "medium",
                        skill_classification.skill,
                        on_chunk=on_chunk,
                        on_stage=on_stage,
                    )
                    result["message_id"] = advisor_message_id
                    result["thoughts"] = "".join(thought_chunks).strip() or None
                    session.append_message(pid, result["response"])
                    await event_queue.put({"_done": True, "result": result})
                except Exception as e:
                    logger.exception(f"chat-stream _run failed for {pid}: {e}")
                    await event_queue.put({
                        "_done": True,
                        "result": {
                            "message_id": advisor_message_id,
                            "persona_id": pid,
                            "persona_name": getattr(persona, "name", pid),
                            "response": f"I ran into a technical issue. Please try again. ({e!s})",
                            "thoughts": "".join(thought_chunks).strip() or None,
                            "used_documents": False,
                            "document_chunks_used": 0,
                            "model_name": getattr(persona.llm, "model_name", "") if persona else "",
                            "grounding": session.response_grounding,
                        },
                    })

            tasks = [asyncio.create_task(_run(pid)) for pid in selected_personas]

            completed = 0
            memory_responses = []
            while completed < len(tasks):
                event = await event_queue.get()
                if isinstance(event, ChatStreamLine):
                    yield event.to_ndjson()
                    continue

                completed += 1
                result = event["result"]
                memory_responses.append({
                    "name": result.get("persona_name") or result.get("persona_id") or "Advisor",
                    "response": result.get("response") or "",
                })
                persisted = PersistMessage(
                    id=result["message_id"],
                    type="advisor",
                    persona_id=result["persona_id"],
                    advisorName=result["persona_name"],
                    content=result["response"],
                    used_documents=result.get("used_documents", False),
                    document_chunks_used=result.get("document_chunks_used", 0),
                    advisor_skill=result.get("advisor_skill") or skill_classification.skill_id,
                    advisor_skill_name=skill_classification.skill.name,
                    thoughts=result.get("thoughts"),
                    model_name=result.get("model_name"),
                    grounding=result.get("grounding"),
                    source_user_message_id=message.user_message_id,
                )
                if message.chat_session_id:
                    if message.retry_of_message_id:
                        await replace_persisted_message(
                            message.chat_session_id,
                            message.retry_of_message_id,
                            persisted,
                        )
                    else:
                        await persist_message(message.chat_session_id, persisted)
                line = ChatStreamLine(
                    type="advisor",
                    data={
                        "message_id": result["message_id"],
                        "persona_id": result["persona_id"],
                        "persona_name": result["persona_name"],
                        "content": result["response"],
                        "thoughts": result.get("thoughts"),
                        "used_documents": result.get("used_documents", False),
                        "document_chunks_used": result.get("document_chunks_used", 0),
                        "model_name": result.get("model_name"),
                        "grounding": result.get("grounding"),
                        "source_user_message_id": message.user_message_id,
                        "advisor_skill": result.get("advisor_skill") or skill_classification.skill_id,
                        "advisor_skill_name": skill_classification.skill.name,
                    },
                )
                yield line.to_ndjson()

            await asyncio.gather(*tasks, return_exceptions=True)

            # Distill this exchange into the student's long-term memory notes
            # (background LLM pass; failures never affect the chat itself).
            try:
                from app.core.library import schedule_chat_memory

                memory_eligible = _is_memory_eligible(
                    message,
                    effective_context_source,
                )
                if not message.retry_of_message_id and memory_eligible:
                    schedule_chat_memory(
                        str(current_user.id), message.user_input, memory_responses
                    )
            except Exception as memory_error:
                logger.warning("Could not schedule chat memory: %s", memory_error)

            session.response_user_message = None
            yield ChatStreamLine(
                type="progress",
                data={"phase": "complete"},
            ).to_ndjson()

        except Exception as exc:
            logger.error(f"chat-stream error: {exc}")
            logger.error(traceback.format_exc())
            yield ChatStreamLine(
                type="error",
                data={"detail": str(exc)},
            ).to_ndjson()

    return StreamingResponse(
        _event_generator(),
        media_type="application/x-ndjson",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@router.post("/switch-chat")
async def switch_to_chat(
    request: SwitchChatRequest, 
    req: Request,
    current_user: User = Depends(get_current_active_user)
):
    """
    Switch to an existing chat session and load its context - FIXED VERSION
    Ensures documents are accessible after switching
    """
    try:
        logger.info(f"Switching to chat session: {request.chat_session_id}")
        
        # Load the chat session into memory context with consistent session ID
        memory_session_id = await get_or_create_session_for_request_async(
            req, 
            chat_session_id=request.chat_session_id,
            user_id=str(current_user.id)
        )
        
        if not memory_session_id:
            raise HTTPException(status_code=404, detail="Chat session not found")
        
        logger.info(f"Loaded chat into memory session: {memory_session_id}")
        
        # Get the loaded session
        session = session_manager.get_session(memory_session_id)
        
        # Verify document access after loading
        rag_stats = session.get_rag_stats()
        logger.info(f"After switch - Session {memory_session_id} has {rag_stats.get('total_documents', 0)} documents")
        
        # Get the original MongoDB chat session to retrieve messages in proper format
        db = get_database()
        chat_session = await db.chat_sessions.find_one({
            "_id": ObjectId(request.chat_session_id),
            "user_id": current_user.id,
            "is_active": True
        })
        
        if not chat_session:
            raise HTTPException(status_code=404, detail="Chat session not found in database")
        
        # Return the messages in the original frontend format from MongoDB
        original_messages = chat_session.get("messages", [])
        
        logger.info(f"Switch successful - {len(original_messages)} messages, {rag_stats.get('total_documents', 0)} documents")
        
        return {
            "status": "success",
            "memory_session_id": memory_session_id,
            "chat_session_id": request.chat_session_id,
            "message_count": len(original_messages),
            "context": {
                "messages": original_messages,  # Return original format messages
                "rag_info": rag_stats
            },
            # Include document access verification
            "document_access": {
                "total_documents": rag_stats.get('total_documents', 0),
                "total_chunks": rag_stats.get('total_chunks', 0),
                "documents": rag_stats.get('documents', []),
                "uploaded_files": session.uploaded_files
            },
            "debug_info": {
                "memory_session_format": memory_session_id,
                "documents_accessible": rag_stats.get('total_documents', 0) > 0,
                "session_loaded": memory_session_id in session_manager.sessions
            }
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error switching to chat {request.chat_session_id}: {e}")
        import traceback
        logger.error(f"Full traceback: {traceback.format_exc()}")
        raise HTTPException(status_code=500, detail="Failed to switch to chat")

@router.post("/new-chat")
async def create_new_chat(
    request: NewChatRequest,
    req: Request,
    current_user: User = Depends(get_current_active_user)
):
    """
    Create a new chat with fresh context
    """
    try:
        # Create a completely new session (no chat_session_id means fresh context)
        memory_session_id = await get_or_create_session_for_request_async(req)
        
        # Ensure the session is completely clean
        session = session_manager.get_session(memory_session_id)
        session.clear_all_data()  # This clears both messages and documents
        
        return {
            "status": "success",
            "memory_session_id": memory_session_id,
            "message": "New chat created with fresh context",
            "context": {
                "messages": [],
                "rag_info": {"total_documents": 0, "total_chunks": 0}
            }
        }
        
    except Exception as e:
        logger.error(f"Error creating new chat: {e}")
        raise HTTPException(status_code=500, detail="Failed to create new chat")

@router.post("/chat/{persona_id}")
async def chat_with_specific_advisor(persona_id: str, input: UserInput, request: Request):
    """Chat with a specific advisor - UPDATED"""
    try:
        if persona_id not in chat_orchestrator.personas:
            raise HTTPException(status_code=404, detail=f"Persona '{persona_id}' not found")

        # Use async session management
        session_id = await get_or_create_session_for_request_async(request)

        if input.chat_session_id:
            await persist_message(
                input.chat_session_id,
                PersistMessage(
                    type="user",
                    content=input.user_input,
                    isExpandRequest=True,
                ),
            )

        result = await chat_orchestrator.chat_with_persona(
            user_input=input.user_input,
            persona_id=persona_id,
            session_id=session_id,
            advisor_skill_id=input.advisor_skill,
        )
        
        # Handle response structure
        if result.get("type") == "single_persona_response" and "persona" in result:
            persona_data = result["persona"]
            if input.chat_session_id:
                await persist_message(
                    input.chat_session_id,
                    PersistMessage(
                        type="advisor",
                        persona_id=persona_data["persona_id"],
                        advisorName=persona_data["persona_name"],
                        content=persona_data["response"],
                        isExpansion=True,
                        advisor_skill=persona_data.get("advisor_skill"),
                        advisor_skill_name=persona_data.get("advisor_skill_name"),
                    ),
                )
            return {
                "persona": persona_data["persona_name"],
                "persona_id": persona_data["persona_id"],
                "response": persona_data["response"]
            }
        elif "persona_id" in result and "response" in result:
            if input.chat_session_id:
                await persist_message(
                    input.chat_session_id,
                    PersistMessage(
                        type="advisor",
                        persona_id=result["persona_id"],
                        advisorName=result["persona_name"],
                        content=result["response"],
                        isExpansion=True,
                        advisor_skill=result.get("advisor_skill"),
                        advisor_skill_name=result.get("advisor_skill_name"),
                    ),
                )
            return {
                "persona": result["persona_name"],
                "persona_id": result["persona_id"],
                "response": result["response"]
            }
        else:
            error_content = "Sorry, I received an unexpected response format. Please try again."
            if input.chat_session_id:
                await persist_message(
                    input.chat_session_id,
                    PersistMessage(type="error", content=error_content),
                )
            return {
                "persona": "System",
                "response": error_content,
            }
            
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in chat_with_specific_advisor: {e}")
        error_content = "Sorry, I encountered an error while expanding the message. Please try again."
        if input.chat_session_id:
            await persist_message(
                input.chat_session_id,
                PersistMessage(type="error", content=error_content),
            )
        return {
            "persona": "System",
            "response": error_content,
        }

@router.post("/reply-to-advisor")
async def reply_to_advisor(reply: ReplyToAdvisor, request: Request):
    """Reply to a specific advisor with proper context - UPDATED"""
    try:
        if reply.advisor_id not in chat_orchestrator.personas:
            raise HTTPException(status_code=404, detail=f"Advisor '{reply.advisor_id}' not found")

        # Handle session management for existing chats
        if reply.chat_session_id:
            session_id = f"chat_{reply.chat_session_id}"
        else:
            session_id = await get_or_create_session_for_request_async(request)
        
        session = session_manager.get_session(session_id)

        if reply.chat_session_id:
            await persist_message(
                reply.chat_session_id,
                PersistMessage(
                    type="user",
                    content=reply.user_input,
                    replyTo=ReplyToRef(
                        advisorId=reply.advisor_id,
                        advisorName=chat_orchestrator.get_persona(reply.advisor_id).name,
                        messageId=reply.original_message_id,
                    ),
                ),
            )

        # Find the original message being replied to for context
        original_message = None
        if reply.original_message_id:
            for msg in session.messages:
                if getattr(msg, 'id', None) == reply.original_message_id:
                    original_message = msg.content
                    break
        
        # Create context-aware input
        contextual_input = reply.user_input
        if original_message:
            contextual_input = f"[Replying to your previous message: '{original_message[:100]}...'] {reply.user_input}"
        
        result = await chat_orchestrator.chat_with_persona(
            user_input=contextual_input,
            persona_id=reply.advisor_id,
            session_id=session_id,
            advisor_skill_id=reply.advisor_skill,
        )
        
        # Handle response structure
        if result.get("type") == "single_persona_response" and "persona" in result:
            persona_data = result["persona"]
            if reply.chat_session_id:
                await persist_message(
                    reply.chat_session_id,
                    PersistMessage(
                        type="advisor",
                        persona_id=persona_data["persona_id"],
                        advisorName=persona_data["persona_name"],
                        content=persona_data["response"],
                        isReply=True,
                        advisor_skill=persona_data.get("advisor_skill"),
                        advisor_skill_name=persona_data.get("advisor_skill_name"),
                        replyTo=ReplyToRef(
                            advisorId=reply.advisor_id,
                            advisorName=persona_data["persona_name"],
                            messageId=reply.original_message_id,
                        ),
                    ),
                )
            return {
                "type": "advisor_reply",
                "persona": persona_data["persona_name"],
                "persona_id": persona_data["persona_id"],
                "response": persona_data["response"],
                "original_message_id": reply.original_message_id
            }
        elif "persona_id" in result and "response" in result:
            if reply.chat_session_id:
                await persist_message(
                    reply.chat_session_id,
                    PersistMessage(
                        type="advisor",
                        persona_id=result["persona_id"],
                        advisorName=result["persona_name"],
                        content=result["response"],
                        isReply=True,
                        advisor_skill=result.get("advisor_skill"),
                        advisor_skill_name=result.get("advisor_skill_name"),
                        replyTo=ReplyToRef(
                            advisorId=reply.advisor_id,
                            advisorName=result["persona_name"],
                            messageId=reply.original_message_id,
                        ),
                    ),
                )
            return {
                "type": "advisor_reply",
                "persona": result["persona_name"],
                "persona_id": result["persona_id"],
                "response": result["response"],
                "original_message_id": reply.original_message_id
            }
        else:
            return {
                "type": "error",
                "persona": "System",
                "response": "I'm having trouble generating a reply right now. Please try again."
            }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in reply_to_advisor: {e}")
        error_content = "Sorry, I encountered an error with your reply. Please try again."
        if reply.chat_session_id:
            await persist_message(
                reply.chat_session_id,
                PersistMessage(type="error", content=error_content),
            )
        return {
            "type": "error",
            "persona": "System",
            "response": error_content,
        }

@router.post("/ask/")
async def ask_question(query: PersonaQuery, request: Request):
    """Ask question - UPDATED"""
    try:
        session_id = await get_or_create_session_for_request_async(request)
        
        result = await chat_orchestrator.chat_with_persona(
            user_input=query.question,
            persona_id=query.persona,
            session_id=session_id
        )
        
        if result["type"] == "single_persona_response":
            response_text = result["persona"]["response"]
        else:
            response_text = result.get("message", "I'm having trouble responding right now.")
        
        return {"response": response_text}
        
    except Exception as e:
        logger.error(f"Error in ask endpoint: {str(e)}")
        return {"response": "I encountered an error. Please try again."}
